### ISSUE TITLE
instructions incorrect - drop nulls not drop column 

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_1.04_activities#1]
current instructions indicate that columns should be dropped, but the solution shows that the data frame is cleaned of null values in those columns. this is in line with the learning points of the lesson at this time where we are learning about null management 
@sandrabosk

**Comment by siandav** [comment]
sorry if unclear which activity i am referring to ! 
this is activity 1 in this lesson 
01-lesson_plans/01-unit_pandas_simple_linear_regression/1.04_data_cleaning_pandas/lesson.md
@sandrabosk

**Comment by sandrabosk** [comment]
@siandav Rephrased to reflect learning goals and solution. Thank you!
