### ISSUE TITLE
instruction unclear

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_1.04_activities#3]
actvity 2 instruction indicates to drop the unwanted columns after reviewing in excel. unclear
i would expect questions along the lines of - should i drop in excel, should i reopen in python and drop there? how do i know i dont want some columns ? acc to what criteria ? is this for the next step of the activity ? 

@sandrabosk

**Comment by sandrabosk** [comment]
@siandav Noted, I will check in with Himanshu.

**Comment by ironhack-edu** [comment]
Reframed the question
