### ISSUE TITLE
unrelated tasks ? 

### ISSUE THREAD

**Issue by siandav** [ironhack-edu/data_1.04_activities#4]
on activity 2 in this lesson it isnt clear how the lambda and excel element are related to eachother ? sorry!

and we had some null management with categorical data from the lesson which isnt applied in the activity 

@sandrabosk

**Comment by sandrabosk** [comment]
@siandav If I understood correctly how Himanshu structured the lesson - at first, we are just introducing the concept of lambdas, and at later points in the lesson, we will explain how we can use lambda expressions for data cleaning. So the second part of the activity is actually just to practice writing lambda expressions (following the same logic we had in the lesson).

I will leave this issue open for Himanshu to add an exercise related to null management with categorical data. In case you have any ideas, please make a PR with improvements. Thank you! 🙌

**Comment by haggarw3** [comment]
I have reframed question 1 and then added another question on replacing null values, as @siandav suggested
